[package]
name = "mio-test"
version = "0.1.0"
authors = ["grzegorz"]

[dependencies]
#mio = "0.5.0"
httparse = "1.1.0"
time = "0.1"
#clippy = "*"

[dependencies.ctrlc]
git = "https://github.com/Detegr/rust-ctrlc"

[dependencies.channels_async]
git = "https://github.com/szagi3891/channels_async-rs"
#path = "../channels_async-rs"

[dependencies.task_async]
git = "https://github.com/szagi3891/task_async-rs"

[dependencies.mio]
git = "https://github.com/carllerche/mio"