[package]
name = "mio-test"
version = "0.1.0"
authors = ["grzegorz"]

[dependencies]
mio = "0.5.0"
simple-signal = "1.0.4"
httparse = "1.1.0"
time = "0.1"

[dependencies.comm]
git = "https://github.com/mahkoh/comm"
